### PR TITLE
Update PyTorch, fastai

### PR DESCRIPTION
**Pull request by rlds-107**

### CODE REVIEW

**Comment by isms** [comment]
@rlds-107 Can you add some detail on why this update is necessary?

**Comment by rlds-107** [comment]
@isms I encountered this error while trying to use the vision module in fastai 2.0.13. The code works with the latest version 2.1.10, which requires torch >=1.7.0

image

**Comment by isms** [comment]
Have you already tried downgrading your local versions to match those in the container and referring to the docs for that version?

This change would affect everyone, possibly unexpectedly, so we are reluctant to accept it.

**Comment by rlds-107** [comment]
@isms Looks like I closed this prematurely. I got the code working on my environment by downgrading to a version of fastcore compatible with fastai 2.0.13 (fastcore==1.0.5). I successfully ran my training code but when submitting to the competition environment it fails with the same error (see attached log line 36)
[log.txt](https://github.com/drivendataorg/noaa-runtime/files/5750222/log.txt)

**Comment by isms** [comment]
Understood - will make these changes since the build appears fine and there are no major breaking version changes. Thanks for opening the PR.

**Comment by isms** [comment]
Changes merged in 8fdc6bc

**Pull request closed without merging**
